### ISSUE TITLE
Option to disable "renamed" event

### ISSUE THREAD

**Issue by callumlocke** [shama/gaze#132]
Would it be possible to add an option to disable "renamed"?

With this option enabled, you would just get a "deleted" event for the old filename followed by an "added" event for the new filename.

**Comment by BluBb-mADe** [comment]
just to clarify the solution, whats wrong with somethink like this?
<code>
gazer.on('rename', function(new, old){
  gazer.emit('deleted', old);
  gazer.emit('added', new);
});
</code>
i know that issue is pretty old but the missing answer bothered me :D

**Comment by callumlocke** [comment]
yeah but it's not that simple. I don't remember the details now, something to do with inconsistent logic for what constitutes a 'rename'.

I eventually moved to [sane](https://github.com/amasad/sane), which only has the raw modify/add/delete events
