### ISSUE TITLE
Required for gulp / grunt watch bump

### ISSUE THREAD

**Issue by shama** [shama/gaze#137]
- [x] Scripts to package pre-built binaries
- [x] Fire different events across multiple instances Ref #104
- [x] Publish fixes with pre-built binaries

---

Above issues are fixed in [navelgazer](https://github.com/shama/navelgazer) and implemented in the [navelgazer branch](https://github.com/shama/gaze/tree/navelgazer) here. Just a few skipped tests to fix.

**Comment by heycalmdown** [comment]
Is this still alive issue? I'm having trouble with constant CPU usage with Gulp. Or can we navelgazer in production instead?

**Comment by polybuildr** [comment]
Ping?
