### ISSUE TITLE
Random ENOENT errors

### ISSUE THREAD

**Issue by oscarotero** [shama/gaze#162]
Hi, I found old issues about this problem but I cannot solve this problem in my case.
The error I get is:

```
fs.js:690
  return binding.lstat(pathModule._makeLong(path));
                 ^
Error: ENOENT, no such file or directory '/Users/oscarotero/www/folk/public/css/.subl141.tmp'
    at Object.fs.lstatSync (fs.js:690:18)
    at /Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/lib/gaze.js:270:21
    at iterate (/Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/lib/helper.js:106:5)
    at Object.forEachSeries (/Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/lib/helper.js:121:3)
    at /Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/lib/gaze.js:267:12
    at ReaddirReq.Req.done (/Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/node_modules/graceful-fs/graceful-fs.js:143:5)
    at ReaddirReq.done (/Users/oscarotero/www/stylecow/stylecow-cli/node_modules/gaze/node_modules/graceful-fs/graceful-fs.js:90:22)
    at Object.oncomplete (fs.js:107:15)
```

I don't know whether this is due a gaze issue or a wrong implementation by me. What I do is some similar to the following:

``` js
var gaze = require('gaze');
var files = css.getImportedFiles(); //returns an array of filenames

gaze(files, function (err, watcher) {
    watcher.on('changed', function (filepath) {
        console.log('changed detected: ' + filepath);

        css.update(); //update the css with the new code

        //adds new @import files dinamically
        css.getImportedFiles().forEach(function (file) {
            if (files.indexOf(file) === -1) {
                files.push(file);
                watcher.add([file]);
            }
        });
    });
});
```

As you can see in the error message, gaze detects changes in files with names like `.subl141.tmp`. I'm using sublimeText to edit the css files so I guess these files are temporary files used by sublime to save the changes, that gaze detects before they are removed.

I'm using gaze 0.6.4 that it's the latest version, released 6 months ago. I can see there are 27 commits since then, maybe this issue is fixed and it's time for a new release.

Thanks so much for this great library

**Comment by psi-4ward** [comment]
`install --save https://github.com/shama/gaze/tarball/master`

```javascript
  gaze('modules/*', function(err, watcher) {
    if(err) return console.error(err);
    console.log('setup');
    watcher.on('all', function(event, filepath) {
      console.log(event, filepath);
    });
  });
```

gives no error but the watcher gets no events regadless of creating / deleting files or folders.

Running Linux 3.18.1 on ext4

**Comment by psi-4ward** [comment]
`gaze('*'` works, any problems with subfolders?

**Comment by shama** [comment]
@psi-4ward Give the `navelgazer` branch a try.

**Comment by psi-4ward** [comment]
doesnt work 
but using navelgazer directly ill receive change events for every action

btw. you sould reference `navelgazer` package in the package.json

**Comment by shama** [comment]
It's a feature branch. Once it's green I'll merge it into master. Any help debugging would be appreciated.

**Comment by psi-4ward** [comment]
if you could tell me how i can debug this?

**Comment by shama** [comment]
Do this to get the latest navelgazer and gaze branches in sync:
```
git clone git://github.com/shama/navelgazer && cd navelgazer && npm i && npm link
cd ..
git clone -b navelgazer git://github.com/shama/gaze && cd gaze && npm i && npm link navelgazer
```

Then give it a try. Thanks!

[node-inspector](https://github.com/node-inspector/node-inspector) is great for setting breakpoints and stepping through code too: `npm i -g node-inspector && node-debug test.js`
