### ISSUE TITLE
gaze error when watch event start

### ISSUE THREAD

**Issue by leandroruel** [shama/gaze#163]
i am having several problems with these errors, all pointing to gaze, follows the screenshot below.

Gaze._watchDir (/var/www/havikhunting/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:289:30)

![captura de tela de 2014-11-26 12 33 47](https://cloud.githubusercontent.com/assets/2836002/5203007/fac755be-7569-11e4-8790-013193098b78.png)

**Comment by spohess** [comment]
I has the same error, but my problem did not was space, my problem was configuration in my operacional system. This code resolve my problem:

```
echo fs.inotify.max_user_watches=582222 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

Source: https://discourse.roots.io/t/gulp-watch-error-on-ubuntu-14-04-solved/3453/2

**Comment by zuher83** [comment]
thanks @spohess,

Solved for me :+1:

**Comment by iliyailiev** [comment]
thanks @spohess 

Solved for me, too !!! Great !!!

**Comment by mkalpana** [comment]
Thanks @spohess

It solved the issue for me :smile:

**Comment by Marcel-Robitaille** [comment]
Thanks @spohess ! Solved for me! :D

**Comment by bozzmob** [comment]
@spohess WOW! Thanks a lot for the solution! :+1:

**Comment by scottyg** [comment]
thanks @spohess !

**Comment by kobleistvan** [comment]
Thanks, it worked!

**Comment by workwsl** [comment]
Thanks. @spohess

**Comment by luisomoreau** [comment]
Thanks

**Comment by mark-slepkov** [comment]
Thanks, @spohess

**Comment by horrigan** [comment]
thanks, @shama

**Comment by KaySchneider** [comment]
thanks @spohess your solution works fine ;)

**Comment by mygu** [comment]
@spohess Thanks a lot for the solution!

**Comment by gitesh-purbia** [comment]
Works for me thanks :)

**Comment by akshaym91** [comment]
Thanks for the solution ! :)

**Comment by strongant** [comment]
Thanks for the solution ! :)

**Comment by rubzat** [comment]
<3 te amooo

**Comment by happilymarrieddad** [comment]
+1   Thanks so much!!!! Solved it for me.

**Comment by doublegunz** [comment]
Thanks for the solution @spohess !

**Comment by konradahodan** [comment]
Solve for me . Thanks
