### ISSUE TITLE
Release 0.6.0 totally screwed up linux support. Many repeated missing events, bogus "removed" events etc.

### ISSUE THREAD

**Issue by nuisanceofcats** [shama/gaze#166]
Using gaze 0.6.4... touch src/*.js when it is watching many files in src will often only register 1. It's basically so broken it isn't even remotely usable for me here.

**Comment by adambratt** [comment]
FIX THIS

**Comment by shama** [comment]
@adambratt Patches welcome.

**Comment by nuisanceofcats** [comment]
IMO this isn't a case of "patches welcome", this is a case where you should totally pull gaze 0.6+ from npm until it can be fixed. Gaze is now completely worthless on Linux, the most popular platform for running node.js, yet when you `npm install gaze` this is the release you get. Anybody who does that will waste so much time. Given the popularity of this package, it doesn't seem acceptable.

You could at least put a warning up saying "Gaze 0.6 and above only work on Mac OS X."

You could also push another 0.5 series release with a higher version as the most recently pushed package becomes the default install in npm rather than the highest version.

**Comment by shama** [comment]
1. `npm i gaze` will install `v0.5.1` (because io.js and node v0.12)
2. "works" is an opinion. `v0.6.x` passed all the tests on Linux/Windows/OSX. So it "works" for me which is why I released it.
3. I don't owe you anything. I say "patches welcome" to let *you* know *you* can just as well fix things but *you* have chosen not to.

**Comment by nuisanceofcats** [comment]
1. Yes obviously, but most people when they start a package do "npm install --save packagename" and assume the latest is the best. Just as a favour to the community I think 0.5 should be the default pulled version, you can fix this simply whether you choose to pull the broken releases or not.
2. That only goes to show the tests suck.
3. Participating in a community isn't about owing stuff, it's about being nice and not wasting people's time.

**Comment by josegonzalez** [comment]
@shama drop whatever it is you're doing and fix this, you owe it to the world for putting up with your terrible, terrible software. I mean, this project [isn't even alive](https://github.com/shama/gaze/issues/182). You should feel bad about releasing this software, free for use and for others to contribute back to, without having it be always bug-free.

**Comment by nuisanceofcats** [comment]
@josegonzalez I think that's a little harsh, I just think a warning on the frontpage and a changing of the default npm version number would be appropriate in this instance until a fix can be made at a convenient time.

**Comment by josegonzalez** [comment]
I mean, he's wasting our time by not doing fixing the issue or telling people otherwise, why should we be kind to him? I bet he doesn't even like competitive apple juggling.

**Comment by shama** [comment]
@nuisanceofcats I'll save you a bunch of time. Stop choosing to use my code.

Closing as wontfix to not waste any more of the OP's time.
