### ISSUE TITLE
new file creation in polling monitor

### ISSUE THREAD

**Issue by demon386** [shama/gaze#183]
When I monitor "all" event, gaze seems to not be able to monitor new file when using polling monitor (I work under Vagrant).

While we all agree that polling is slow, is it possible to add an option, for polling monitor, to rescan indexed files under a certain interval?

**Comment by shama** [comment]
Which version of gaze? Is it just new files not being watched with polling? Are you getting other events? Could you provide an example so I can reproduce the issue? It shouldn't need to rescan.

Although you could just create an interval that destroys and creates a new instance to force rescanning. I'm not sure how efficient that would be though.

**Comment by demon386** [comment]
It's NFS in vagrant, thus inotify won't sense the change. How does polling option able to detect that without rescaning?

I'm on the way and will provide an example later.

**Comment by shama** [comment]
Thanks, which version of gaze?

Sorry I must have misunderstood "rescan." What do you mean by "rescan?"

**Comment by demon386** [comment]
I can reproduce under OSX too.

first:
```
mkdir /Users/username/forgaze
touch /Users/username/forgaze/hello
```

then launch gaze:

gaze code:
```{javascript}
var Gaze = require('gaze').Gaze;
var gaze = new Gaze('/Users/username/forgaze/**/*', {'mode': 'poll'})

gaze.on('ready', function(watcher) {
    console.log("start watching...")
})

gaze.on('all', function(event, filepath) {
    console.log(event + ": " + filepath)
})
```

After that, If I edit /Users/username/forgaze/hello, It will sense.

But If I do
```
touch /Users/username/forgaze/world
```

and edit that file, gaze won't react.

node --version => v0.12.0
npm list -g | grep 'gaze' => gaze@0.5.1

**Comment by demon386** [comment]
I say "rescan" because from this phenomenon I presume there's some indexing mechanism for a list of files to watch, when polling monitor is used. This makes newly added files unnoticed, and require a re-scan to update that index.

**Comment by shama** [comment]
It could be the absolute path. Technically, gaze doesn't take file paths but rather file patterns. Try this instead:

```js
var gaze = new Gaze('**/*', {'mode': 'poll', cwd: '/Users/username/forgaze/'})
```

**Comment by demon386** [comment]
Works now!! Thanks.

This is subtle and could be better documented.
