### ISSUE TITLE
Gaze not keeping process alive?

### ISSUE THREAD

**Issue by aleclarson** [shama/gaze#184]
I'm using **io.js v1.5.1** with **gaze v0.5.1**.

The globs are `spec/**.coffee` and `src/**.coffee` and both have matches.

`Done, without errors.` is logged immediately after I call `gaze(...)`.

Have you seen this problem before? Thanks.

**Comment by shama** [comment]
Mind posting a full code example I could try?

**Comment by aleclarson** [comment]
I should have mentioned I'm attempting to use `gaze(...)` in a Grunt task.

I assumed `gaze` would keep the process open for me.

My solution is to call `this.async()` to keep the task running forever.

Sorry bout that! :v:
