### ISSUE TITLE
Can't specify options for minimatch

### ISSUE THREAD

**Issue by arwong09** [shama/gaze#186]
Gaze uses minimatch for its matching, but does not allow a way to specify options to for minimatch, only a pattern.  Minimatch can take a pattern and options for specific matching rules, i.e. {nocase: true} will make the matching case insensitive.

**Comment by shama** [comment]
`options` is a optional secondary parameter in which you can specify options for minimatch. See https://github.com/shama/gaze#gazepatterns-options-callback
