### ISSUE TITLE
patch 0.5.X release to fix maxListeners

### ISSUE THREAD

**Issue by timelf123** [shama/gaze#193]
gaze@0.5.x doesn't pay attention to maxListeners: 0. It should set them to infinite but currently ignores the option. This is fixed in 0.6.X, but 0.6.x is unable at the moment

Is it possible to release a patch for 0.5.X?

**Comment by shama** [comment]
Done on https://github.com/shama/gaze/commit/5c71641d5449873df3b0c36ef73ff100da399703
