### ISSUE TITLE
gulp plugin?

### ISSUE THREAD

**Issue by eskhool** [shama/gaze#194]
Hi,
 Although the front page says that gaze is used by gulp, it doesn't appear that way anymore. Am I right in assuming that gaze is native on linux where chokidar is not (ok you may not be able to answer to the 2nd part)...If so, then is there work already done to integrate gaze into gulpjs? asking because I couldn't find any plugin and gulp-watch list chokidar as the current watcher.

**Comment by shama** [comment]
gulp itself currently uses gaze through [glob-watcher](https://www.npmjs.com/package/glob-watcher). [gulp-watch](https://www.npmjs.com/package/gulp-watch) is something else and at one time did use gaze but now uses chokidar. gulp will also likely switch to chokidar.

gaze >= 0.6 uses native addons for OSX, Linux and Windows. Where gaze 0.5.1 (the version gulp uses) only uses the native file watching events (provided through Node.js) for some operations.
