### ISSUE TITLE
drop node 0.8 support?

### ISSUE THREAD

**Issue by marneborn** [shama/gaze#197]
I'm trying to speed up negate of whole branches of my tree (https://github.com/shama/gaze/issues/109)

There is a relatively straight forward fix, but it's not compatible with node 0.8.

https://github.com/cowboy/node-globule uses https://github.com/isaacs/node-glob which has added an ignore option that stops traversing down a branch of the tree. My runtime goes from 4sec to 0.3 with this change to the package.json.

I have PR (https://github.com/cowboy/node-globule/pull/19) to upgrade to glob 5.0.14 to get this.

Unfortunately any version of glob with this option is not compatible with node 0.8, (well, the npm that comes with 0.8) as there are ^s in the package.json.
So travis fails globule with my PR in node 0.8, 0.10 is fine.
Even if @cowboy takes this PR, changing gaze to use it will make gaze start failing the travis node 0.8 run.

Would you consider dropping node 0.8 support to take this?
Or should i try something else?

**Comment by shama** [comment]
Node v0.8 support has been dropped.
