### ISSUE TITLE
0.6 doesn't work on windows

### ISSUE THREAD

**Issue by vendethiel** [shama/gaze#198]
So, I tried to update this module because I had been using 0.5.0 for the longest time, but this broke everything on windows for me.

My code:

```js
require('gaze')(['metadata.js', 'src/**/*', 'lib/**/*', 'Slakefile'])(function () {
  console.log('Watching files...');
  this.on('all', console.log.bind(console));
});
```

This prints "Watching files..." as many times as there are files, then nothing is printed when I try to trigger an event..?

**Comment by shama** [comment]
Which version of Windows and Node.js or io.js?

Also this part looks off:
```js
require('gaze')(['metadata.js', 'src/**/*', 'lib/**/*', 'Slakefile'])(function () {
```
I think it should be:
```js
require('gaze')(['metadata.js', 'src/**/*', 'lib/**/*', 'Slakefile'], function () {
```

**Comment by vendethiel** [comment]
yes, sorry, that was a translation mistake. Windows 8.1, node 0.12.4
