### ISSUE TITLE
Not watching anything

### ISSUE THREAD

**Issue by runemadsen** [shama/gaze#201]
I have a very simple script running in a folder called `example` that looks like this:

```
/javascripts
   myfile.js
/stylesheets
   myfile.scss
```

When I run the following, gaze doesn't watch any files at all.

```js
console.log(process.cwd());

gaze('stylesheets/myfile.scss', function(err, watcher) {

    console.log("Watching assets")

    this.watched(function(err, watched) {
      console.log(watched);
    });

    this.on('all', function(event, filepath) {
      console.log('changed ' + filepath);
    });
});
```

The `console.log` outputs the correct `examples` dir as the `cwd`, so I'm in the right folder. No other globs work.

What's wrong with this?

**Comment by shama** [comment]
The glob pattern `*` will only match files in the `cwd`. If you want to watch files in subfolders use `**/*` (although be careful as that is going to match every folder/file in your `cwd). A more specific pattern would be `**/*.{js,scss}`.

https://en.wikipedia.org/wiki/Glob_(programming)

**Comment by runemadsen** [comment]
I just changed the glob to another version that doesn't work. As I said, no files are watched no matter what glob pattern I use. I've tried all of these:

- `stylesheets/*.scss`
- `javascripts/*.js`
- `**/*.scss`

Nothing seems to work. `this.watched` is never triggered.

**Comment by shama** [comment]
Which OS and version are you on? Which version of Node.js? Which version of gaze? Are any errors being reported?

**Comment by runemadsen** [comment]
These are my specs:

- node `v4.2.0`
- npm `2.14.7`
- gaze `0.5.2`
- OSX 10.10.5

No errors reported at all. This is the only output I get from running the script above:

```
/Users/runemadsen/Projects/phew/example
Watching assets
```

No files watched at all no matter what glob I use. As you can see, the path is correct.

**Comment by shama** [comment]
Ah ha, sorry the interface from `gaze@0.5.2` has changed from sync to async. Try this instead:

```js
gaze('stylesheets/myfile.scss', function(err, watcher) {
    var watched = this.watched();
    console.log(watched);
});
```

**Comment by runemadsen** [comment]
Awesome. That works! Thanks so much for the quick replies. Very much appreciated.

**Comment by shama** [comment]
I've updated the readme with notes about the change too. Thanks!
