### ISSUE TITLE
Cannot watch absolute path on added event

### ISSUE THREAD

**Issue by jetzhliu** [shama/gaze#203]
when I watch on absolute path, it does not work with add event, but relative path does.
I can't find any hint at Readme.md, is this a feature?
```
gaze('/Users/me/Downloads/gaze-master/test/**/*', function(err, watcher) {
  // it doesn't not work, but `test/**/*` will
  this.on('added', function(filepath) {
    console.log(filepath);
  });
});
```
My Machine Environment:
Mac OS X 10.11
node: v4.1.0
gaze: v0.6.4 & v0.5.2

**Comment by shama** [comment]
It is because it works upon file patterns instead of file paths. Try this instead:

```js
gaze('test/**/*', { cwd: '/Users/me/Downloads/gaze-master/' }, function(err, watcher) {
  this.on('added', function(filepath) {
    console.log(filepath);
  });
});
```

**Comment by jetzhliu** [comment]
Thanks very much!!
