### ISSUE TITLE
Please bump version number and push to NPM

### ISSUE THREAD

**Issue by richb-hanover** [shama/gaze#212]
As noted in https://github.com/shama/gaze/issues/210 the package.json file was recently updated to refer to globule 0.2.0, but that update never seems to have gone to the main npm.

I believe (but I'm new to this) that bumping the version number on gaze and re-pushing to npm will solve the problem. Thanks!

**Comment by shama** [comment]
Thanks for the ping! The code that lives in the `master` branch is an updated version of `0.5.4`. Slated to be released as `1.0.0` and latest. It will fix warnings and some other minor things. Unfortunately the tests are failing on Windows. So I can't yet publish it.

If you have access to a Windows machine I would appreciate some help debugging the failing tests. Thanks!

**Comment by richb-hanover** [comment]
Alas, my Windows chops are not good enough to debug file system troubles. Sorry - and thanks for looking at this.

**Comment by shouze** [comment]
@shama what is the problem with windows?

Should it be possible to only upgrade lodash in a separate PR & patch release (0.5.x)? I have deprecation warnings during my npm install:
```shell
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
```

Thx.

**Comment by shouze** [comment]
@shama I've made a PR: https://github.com/shama/gaze/pull/213

**Comment by chebum** [comment]
> Unfortunately the tests are failing on Windows

@shama I don't see any falling tests on Windows 10 as of today. All 54 assertions passed in 30 seconds. Where to look for the problem?

**Comment by shama** [comment]
This issue was related to another version of this lib that had some failing tests. I ended up just releasing an updated version of 0.5.
