### ISSUE TITLE
Deprecation warnings and other issues

### ISSUE THREAD

**Issue by ghost** [shama/gaze#230]
@shama  @kaelzhang  @lancejpollard @tschaub @groner @cowboy @alexgorbatchev 

If I try to run the tests on Windows, I can trigger this one: 

```js
(node:2208) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
```

This is on NodejS v. 6.7.0. Then I upgraded to NodeJS v. 7.0, and got even more deprecation warnings, and things also stopped working.

Dunno how to reproduce it, but 2 of my files **got deleted** - *not refreshed on change* - as I expected. This on NodejS 7.0.  When I tried again with some dummy test files, some of this files was gone too!!!

I also got complains regarding the EventEmitter telling me that "domain" is not valid etc. This part of the EventEmitter code was complaining: https://github.com/nodejs/node/blob/master/lib/events.js#L46-L48

Is there anyway of spawn the child process and run this on each single CPU thread?

**Comment by shama** [comment]
Please avoid mass pinging people. Nearly all the people you've pinged are not actively involved in the development of this library and it just creates noise for them.

Could you provide code that you tried to produce those deprecation warnings?

As for spawning child processes, Node.js provides that, please read their docs.

**Comment by crazyhuggins** [comment]
@shama If you use a windows computer and run the tests on this repo you will get the warnings. At least if you are using NodejS 7. You would also get a node:6956 issue. To many listeners that can cause a memory leak.
