### ISSUE TITLE
Gaze crashes when a non-empty folder is permanently removed

### ISSUE THREAD

**Issue by kireerik** [shama/gaze#248]
No event is fired when a non-empty folder is deleted. Once it is deleted from the recycle bin I get the following error:
```shell
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (fs.js:1372:28)
Emitted 'error' event at:
    at Gaze.emit (node_modules\gaze\lib\gaze.js:102:32)
    at Gaze._handleError (node_modules\gaze\lib\gaze.js:468:15)
    at FSWatcher.<anonymous> (node_modules\gaze\lib\gaze.js:328:12)    at FSWatcher.emit (events.js:182:13)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1378:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

System: `Windows 10 Pro 1083`
Gaze version: `1.1.3`

Note: @paulmillr's and @es128's [chokidar](https://github.com/paulmillr/chokidar), @balupton's @bevry's [watchr](https://github.com/bevry/watchr) and maybe @amasad's [sane](https://github.com/amasad/sane) (I don't remember if I tried it or not.) has the exact same issue. I did't tried [watch](https://github.com/mikeal/watch) and [node-pathwatcher](https://github.com/atom/node-pathwatcher), but they probably has this issue as well.

**Comment by balupton** [comment]
What about Facebook’s watchman?

**Comment by shama** [comment]
`EPERM: operation not permitted, watch`

There really isnt anything we can do to get around file system permissions. If you don't want to see the error or would like to handle the error differently, add an event listener for the error and handle it.

**Comment by kireerik** [comment]
@balupton I didn't tried it.

@shama The issue also exists if I force delete the folder. Yes it is definitely a potential workaround.

**Comment by kireerik** [comment]
I think we should probably keep this issue opened since it can be related to the [other issue](https://github.com/shama/gaze/issues/249) I have reported.

I can see somewhat similar, but really old issues however which are probably resolved and are closeable by now.

**Comment by shama** [comment]
I dont see how it is related and I cannot fix `EPERM` for you. If the library doesnt have permissions on your machine it simply doesnt have permissions. Either give it permissions, handle the error or ignore the error.

**Comment by kireerik** [comment]
I don't want you to fix this for me. Also it looks like to me that Gaze is trying to watch something which was just deleted. Permanently deleting an empty directory works without any issue, but when you have at least one file in the folder it doesn't works (at least under Windows).

**Comment by kireerik** [comment]
Related issue: https://github.com/shama/gaze/issues/44
