### ISSUE TITLE
New files not picked up from VirtualBox shared folders under Linux

### ISSUE THREAD

**Issue by irskep** [shama/gaze#32]
My dev environment is a VirtualBox (Vagrant) Ubuntu instance that runs my server, runs `grunt` to compile assets, etc. I use `grunt-contrib-watch` to keep my files updated, which in turn uses `gaze`. (OS X host.)

My repository is mounted as a shared folder inside the VirtualBox instance, which does not work with inotify reliably. The symptom is that while file _changes_ are picked up by the watch process, added files are not.

Would it be feasible to have a polling-based fallback?

I hope I've explained the issue adequately and am asking in the right project.

**Comment by laskos** [comment]
@shema: ```mode: pool``` doesnt work for me :( Added files still cant be detected by gazle. I am running it on Vagrant with NFS files sync on OSX 10.8.5

**Comment by adamziel** [comment]
Same here

**Comment by dr0bz** [comment]
yep not working on a nfs share in vagrant
