### ISSUE TITLE
Why fs.watchFile instead of fs.watch?

### ISSUE THREAD

**Issue by gurdiga** [shama/gaze#69]
Hey guys!

I’ve seen my `grunt watch` taking 10+% of the CPU since a while (with 165 watched files), and today digging into it a bit got me to the `interval` option of Gaze constructor, and to `fs.watchFile` call in [Gaze.prototype._pollFile()](https://github.com/shama/gaze/blob/bfd0ccc5353a569c287d3817ba6002b609b9dc6a/lib/gaze.js#L325). Setting the `interval` to 1000 got Node’s CPU usage to ~0.0%, so the issue is solved, but I’m still left with the question:

> Since `fs.watchFile` has this CPU issue, why not use `fs.watch` instead as [Node’s API documentation recommends](http://nodejs.org/api/fs.html#fs_fs_watchfile_filename_options_listener)?

I have even hacked my local `node_modules/grunt-contrib-watch/node_modules/gaze/lib/gaze.js` and replaced removed “File” from `fs.watchFile` and it still seems to work (OS X 10.8.5). I also see that [`Gaze.prototype._watchDir` uses `fs.watch`](https://github.com/shama/gaze/blob/bfd0ccc5353a569c287d3817ba6002b609b9dc6a/lib/gaze.js#L285), so it’s probably not [the consistency caveat mentioned in the Node’d API documentation](http://nodejs.org/api/fs.html#fs_caveats), and now I’m even more intrigued. :)

I understand this is not a question directly related to this project, I’m just hoping that you guys have found an answer you could share.

UPDATE: Umm… my hack seems not to work actually… :-|

**Comment by sryze** [comment]
Hello, has there been any progress on the next version? I use gulp with polling interval = 500ms and I still see around 5% CPU usage constantly while using `gulp.watch()`. I checked the source code and it seems like gaze is still using `fs.watchFile()` unconditionally. 

So I was wondering if the situation improved over the last 4 years. I know I could just increase the interval to 1 second or something but that would create a huge delay for me.

Is anybody looking into this currently? I can give it a try myself, although I don't have a ton of experience with Node.js.
